# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mukil Elango
email: mukilane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mukil's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mukilane.github.io" # the base hostname & protocol for your site
twitter_username: mukilane
github_username:  mukilane
greeting: "" # Display special messages
angular_version: "1.6.1" # Version of AngularJS used 
firebase_version: "3.6.6"
exclude: ["package.json",
          "node_modules",
          "gulpfile.js",
          "sw-precache-config.js"]
ampdir: amp # Amp files are stored here
# Collections
collections:
  project:
    output: true

# Build settings
markdown: kramdown

exculde: [vendor]